export const frontEndProjects = [
  {
    name: 'Portfolio',
    image: '../../assets/nav-background.jpg',
    description:
      'This portfolio code and demo made with Angular and material guidelines.',
    demoUrl: 'https://angular-portfolio-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/angular-portfolio',
    downloadUrl: 'https://github.com/Luis-Hermida/angular-portfolio',
    technologies: ['Angular', 'Material', 'SCSS'],
    projectImages: [
      'https://i.imgur.com/AOGaaad.jpg',
      'https://i.imgur.com/HU2VoOp.jpg',
    ],
  },
  {
    name: 'Responsive Navbar',
    image: '../../assets/nav-background.jpg',
    description:
      'A responsive header made with CSS that have different design based if mobile.',
    demoUrl: 'https://css-animated-navbar-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/css-animated-navbar',
    downloadUrl: 'https://github.com/Luis-Hermida/css-animated-navbar',
    technologies: ['CSS'],
    projectImages: [],
  },
  {
    name: 'CSS Animations',
    image: '../../assets/nav-background.jpg',
    description:
      'Different pages with different kind of animations made with CSS.',
    demoUrl: 'https://css-animations-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/css-animations',
    downloadUrl: 'https://github.com/Luis-Hermida/css-animations',
    technologies: ['CSS'],
    projectImages: [],
  },
  {
    name: 'CSS Cards',
    image: '../../assets/nav-background.jpg',
    description:
      'Different types of cards with different effects made with CSS.',
    demoUrl: 'https://css-cards-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/css-cards',
    downloadUrl: 'https://github.com/Luis-Hermida/css-cards',
    technologies: ['CSS'],
    projectImages: [],
  },
  {
    name: 'CSS Effects',
    image: '../../assets/nav-background.jpg',
    description: 'Different pages with different types of CSS effects.',
    demoUrl: 'https://css-effects-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/css-effects',
    downloadUrl: 'https://github.com/Luis-Hermida/css-effects',
    technologies: ['CSS'],
    projectImages: [],
  },
  {
    name: 'Fadeout Scroll',
    image: '../../assets/nav-background.jpg',
    description:
      'Single page that shows a video that fades while the user is scrolling.',
    demoUrl: 'https://css-fadeout-scroll-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/css-fadeout-scroll',
    downloadUrl: 'https://github.com/Luis-Hermida/css-fadeout-scroll',
    technologies: ['CSS'],
    projectImages: [],
  },
  {
    name: 'Form Styles',
    image: '../../assets/nav-background.jpg',
    description:
      'Pages that shows different inputs or form related elements styled or with some effects.',
    demoUrl: 'https://css-form-styles-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/css-form-styles',
    downloadUrl: 'https://github.com/Luis-Hermida/css-form-styles',
    technologies: ['CSS'],
    projectImages: [],
  },
  {
    name: 'CSS Grids',
    image: '../../assets/nav-background.jpg',
    description: 'Different types of grids made with CSS.',
    demoUrl: 'https://css-grids-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/css-grids',
    downloadUrl: 'https://github.com/Luis-Hermida/css-grids',
    technologies: ['CSS'],
    projectImages: [],
  },
  {
    name: 'Omnifood Project',
    image: '../../assets/nav-background.jpg',
    description:
      'Website that simulates a company that offers a food related service.',
    demoUrl: 'https://css-omnifood-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/css-omnifood',
    downloadUrl: 'https://github.com/Luis-Hermida/css-omnifood',
    technologies: ['CSS', 'JQuery', 'PHP'],
    projectImages: [],
  },
  {
    name: 'Parallax Scrolling',
    image: '../../assets/nav-background.jpg',
    description:
      'Websites that contains different types of parallax effects while scrolling.',
    demoUrl: 'https://css-parallax-scrolling-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/css-parallax-scrolling',
    downloadUrl: 'https://github.com/Luis-Hermida/css-parallax-scrolling',
    technologies: ['CSS'],
    projectImages: [],
  },
  {
    name: 'Progress Scroll',
    image: '../../assets/nav-background.jpg',
    description:
      'Effect that changes the default style of the scrollbar to a loading one.',
    demoUrl: 'https://css-progress-scroll-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/css-progress-scroll',
    downloadUrl: 'https://github.com/Luis-Hermida/css-progress-scroll',
    technologies: ['CSS'],
    projectImages: [],
  },
  {
    name: 'SVG Animation',
    image: '../../assets/nav-background.jpg',
    description: 'Effects that change an SVG icon on hover',
    demoUrl: 'https://css-svg-animation-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/css-svg-animation',
    downloadUrl: 'https://github.com/Luis-Hermida/css-svg-animation',
    technologies: ['CSS'],
    projectImages: [],
  },
  {
    name: 'Budget App',
    image: '../../assets/nav-background.jpg',
    description: 'Simple budget app that calculates income and expenses.',
    demoUrl: 'https://js-budget-app-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/js-budget-app',
    downloadUrl: 'https://github.com/Luis-Hermida/js-budget-app',
    technologies: ['JavaScript', 'Bootstrap'],
    projectImages: [],
  },
  {
    name: 'Analog Clock',
    image: '../../assets/nav-background.jpg',
    description: 'Functional analog clock made with vanilla JavaScript.',
    demoUrl: 'https://js-budget-app-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/js-clock',
    downloadUrl: 'https://github.com/Luis-Hermida/js-clock',
    technologies: ['JavaScript'],
    projectImages: [],
  },
  {
    name: 'Pong Game',
    image: '../../assets/nav-background.jpg',
    description: 'Pong game with 4 levels made with vanilla JavaScript.',
    demoUrl: 'https://js-pong-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/js-pong',
    downloadUrl: 'https://github.com/Luis-Hermida/js-pong',
    technologies: ['JavaScript'],
    projectImages: [],
  },
  {
    name: 'Rock Paper Scissors',
    image: '../../assets/nav-background.jpg',
    description: 'Rock Paper Scissors game made with JavaScript.',
    demoUrl: 'https://js-rock-paper-scissors-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/js-rock-paper-scissors',
    downloadUrl: 'https://github.com/Luis-Hermida/js-rock-paper-scissors',
    technologies: ['JavaScript', 'CSS'],
    projectImages: [],
  },
  {
    name: 'Shopping Cart',
    image: '../../assets/nav-background.jpg',
    description: 'Website with a functional shopping cart.',
    demoUrl: 'https://js-shopping-cart-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/js-shopping-cart',
    downloadUrl: 'https://github.com/Luis-Hermida/js-shopping-cart',
    technologies: ['JavaScript', 'CSS'],
    projectImages: [],
  },
  {
    name: 'Snake Game',
    image: '../../assets/nav-background.jpg',
    description: 'Classic game snake made in JavaScript.',
    demoUrl: 'https://js-snake-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/js-snake',
    downloadUrl: 'https://github.com/Luis-Hermida/js-snake',
    technologies: ['JavaScript', 'Node.js'],
    projectImages: [],
  },
  {
    name: 'Theme Switcher',
    image: '../../assets/nav-background.jpg',
    description: 'Theme switcher with 2 themes with 2 variants.',
    demoUrl: 'https://js-theme-switcher-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/js-theme-switcher',
    downloadUrl: 'https://github.com/Luis-Hermida/js-theme-switcher',
    technologies: ['JavaScript'],
    projectImages: [],
  },
  {
    name: 'Unbeatable Tic Tac Toe',
    image: '../../assets/nav-background.jpg',
    description: 'Unbeatable tic tac toe AI using minimax algorithm.',
    demoUrl: 'https://js-unbeatable-tictactoe-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/js-unbeatable-tictactoe',
    downloadUrl: 'https://github.com/Luis-Hermida/js-unbeatable-tictactoe',
    technologies: ['JavaScript'],
    projectImages: [],
  },
  {
    name: 'Advanced Navbar',
    image: '../../assets/nav-background.jpg',
    description:
      'Advanced navigation bar using React and react-transition-group library.',
    demoUrl: 'https://react-advanced-navbar-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/react-advanced-navbar',
    downloadUrl: 'https://github.com/Luis-Hermida/react-advanced-navbar',
    technologies: ['React'],
    projectImages: [],
  },
  {
    name: 'Auth0 Login',
    image: '../../assets/nav-background.jpg',
    description:
      'Auth0 login with different endpoints in express to validate user access.',
    demoUrl: 'https://react-auth0-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/react-auth0',
    downloadUrl: 'https://github.com/Luis-Hermida/react-auth0',
    technologies: ['React', 'Auth0', 'Express.js'],
    projectImages: [],
  },
  {
    name: 'Author Quiz',
    image: '../../assets/nav-background.jpg',
    description:
      'Quiz and form to add more questions about authors and their books.',
    demoUrl: 'https://react-author-quiz-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/react-author-quiz',
    downloadUrl: 'https://github.com/Luis-Hermida/react-author-quiz',
    technologies: ['React'],
    projectImages: [],
  },
  {
    name: 'Autocomplete Input',
    image: '../../assets/nav-background.jpg',
    description: 'Country input that autocompletes with user input.',
    demoUrl: 'https://react-autocomplete-input-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/react-autocomplete-input',
    downloadUrl: 'https://github.com/Luis-Hermida/react-autocomplete-input',
    technologies: ['React'],
    projectImages: [],
  },
  {
    name: 'GitHub Cards',
    image: '../../assets/nav-background.jpg',
    description:
      'Form that uses GitHub API to get you a GitHub profile looking by the username.',
    demoUrl: 'https://react-github-cards-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/react-github-cards',
    downloadUrl: 'https://github.com/Luis-Hermida/react-github-cards',
    technologies: ['React', 'Axios'],
    projectImages: [],
  },
  {
    name: 'React Restaurant',
    image: '../../assets/nav-background.jpg',
    description:
      'Website that simulates a restaurant page with serveral routes and functional forms.',
    demoUrl: 'https://react-restaurant-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/react-restaurant',
    downloadUrl: 'https://github.com/Luis-Hermida/react-restaurant',
    technologies: ['React', 'Redux', 'Express.js'],
    projectImages: [],
  },
  {
    name: 'Star Match Game',
    image: '../../assets/nav-background.jpg',
    description:
      'Game where you have to count the number of stars before the time runs out.',
    demoUrl: 'https://react-star-match-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/react-star-match',
    downloadUrl: 'https://github.com/Luis-Hermida/react-star-match',
    technologies: ['React'],
    projectImages: [],
  },
  {
    name: 'Stopwatch',
    image: '../../assets/nav-background.jpg',
    description:
      'Website that works as a normal stopwatch. Made using React Hooks.',
    demoUrl: 'https://react-stopwatch-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/react-stopwatch',
    downloadUrl: 'https://github.com/Luis-Hermida/react-stopwatch',
    technologies: ['React'],
    projectImages: [],
  },
  {
    name: 'Tetris',
    image: '../../assets/nav-background.jpg',
    description: 'Tetris Game that scales up difficulty and register score.',
    demoUrl: 'https://react-tetris-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/react-tetris',
    downloadUrl: 'https://github.com/Luis-Hermida/react-tetris',
    technologies: ['React'],
    projectImages: [],
  },
  {
    name: 'Tic Tac Toe',
    image: '../../assets/nav-background.jpg',
    description: 'React tutorial with additional challenges.',
    demoUrl: 'https://react-tictactoe-lahn.herokuapp.com/',
    codeUrl: 'https://github.com/Luis-Hermida/react-tictactoe',
    downloadUrl: 'https://github.com/Luis-Hermida/react-tictactoe',
    technologies: ['React'],
    projectImages: [],
  },
];
